version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 180
      runas: root
    - location: shell_scripts/ALLLLX.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: shell_scripts/BACKUP.sh
      timeout: 180
      runas: root

