version: 0.0
os: linux
files:
  - source: /kanshi-process/cmd/main.go
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 180
      runas: root
    - location: scripts/start_server
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 180
      runas: root

