version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-use/
hooks:
  ALLLLD:
    - location: shell_scripts/ALLLLD.sh
  ALLLLX:
    - location: shell_scripts/ALLLLX.sh
  CHIKUSEKICHECK:
    - location: shell_scripts/CHIKUSEKICHECK.sh
  DATADEL:
    - location: shell_scripts/DATADEL.sh
  DATATEISEISTART:
    - location: shell_scripts/DATATEISEISTART.sh      
