package configs

import (
	"errors"
	"github.com/stretchr/testify/assert"
	"start-ecs/configs"
	"testing"
)

func Test_TickSystem_Validate(t *testing.T) {
	tests := []struct {
		name   string
		args   configs.TickSystem
		expect error
	}{
		{
			name: "TK_SYSTEM_QUOTE_CODES_DEFINITION_TICK_KEI1_OBJECT is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_QUOTE_CODES_DEFINITION_TICK_KEI1_OBJECT is required"),
		},
		{
			name: "TK_SYSTEM_QUOTE_CODES_DEFINITION_KEHAI_KEI1_OBJECT is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_QUOTE_CODES_DEFINITION_KEHAI_KEI1_OBJECT is required"),
		},
		{
			name: "TK_SYSTEM_QUOTE_CODES_DEFINITION_TICK_KEI2_OBJECT is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_QUOTE_CODES_DEFINITION_TICK_KEI2_OBJECT is required"),
		},
		{
			name: "TK_SYSTEM_QUOTE_CODES_DEFINITION_KEHAI_KEI2_OBJECT is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei2Object: "",
				BP03FirstRunningTypeEnvKeys:         []string{},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_QUOTE_CODES_DEFINITION_KEHAI_KEI2_OBJECT is required"),
		},
		{
			name: "TK_SYSTEM_BP03_PARAMS_FIRST_RUNNING_TYPE_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP03_PARAMS_FIRST_RUNNING_TYPE_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP03_PARAMS_SECOND_RUNNING_TYPE_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP03_PARAMS_SECOND_RUNNING_TYPE_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP05_PARAMS_FIRST_RUNNING_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP05_PARAMS_FIRST_RUNNING_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP05_PARAMS_SECOND_RUNNING_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP05_PARAMS_SECOND_RUNNING_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP05_PARAMS_THIRD_RUNNING_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP05_PARAMS_THIRD_RUNNING_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP05_PARAMS_FOURTH_RUNNING_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP05_PARAMS_FOURTH_RUNNING_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP06_PARAMS_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP06_PARAMS_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP07_PARAMS_FIRST_RUNNING_TYPE_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP07_PARAMS_FIRST_RUNNING_TYPE_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP07_PARAMS_SECOND_RUNNING_TYPE_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP07_PARAMS_SECOND_RUNNING_TYPE_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_BP07_PARAMS_THIRD_RUNNING_TYPE_ENV_KEYS is empty",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_BP07_PARAMS_THIRD_RUNNING_TYPE_ENV_KEYS is required"),
		},
		{
			name: "TK_SYSTEM_MAX_RETRY_WAIT_TIME is 0",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         0,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_MAX_RETRY_WAIT_TIME is required"),
		},
		{
			name: "TK_SYSTEM_RETRY_WAIT_TIME is 0",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       0,
				MaxCountTime:                        3,
			},
			expect: errors.New("TK_SYSTEM_RETRY_WAIT_TIME is required"),
		},
		{
			name: "TK_SYSTEM_MAX_CHECK_COUNT_TIME is 0",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        0,
			},
			expect: errors.New("TK_SYSTEM_MAX_CHECK_COUNT_TIME is required"),
		},
		{
			name: "Validate successfully",
			args: configs.TickSystem{
				QuoteCodesDefinitionTickKei1Object:  "environment_variables/quote_code_definition_tick_kei1.json",
				QuoteCodesDefinitionKehaiKei1Object: "environment_variables/quote_code_definition_kehai_kei1.json",
				QuoteCodesDefinitionTickKei2Object:  "environment_variables/quote_code_definition_tick_kei2.json",
				QuoteCodesDefinitionKehaiKei2Object: "environment_variables/quote_code_definition_kehai_kei2.json",
				BP03FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_KUBUN", "TICK_HASSIN", "TICK_CREATE_DATE", "TICK_CREATE_TIME", "TICK_START_INDEX"},
				BP03SecondRunningTypeEnvKeys:        []string{"TICK_OPERATION_TYPE", "TICK_TARGET_SYSTEM", "TICK_FOLDER_PATH"},
				BP05FirstRunningTypeEnvKeys:         []string{"TICK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_TARGET_KEI"},
				BP05SecondRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST"},
				BP05ThirdRunningTypeEnvKeys:         []string{"TK_OPERATION_TYPE", "TK_DATE_REQUEST", "TK_FILE_LIST", "TK_TARGET_KEI"},
				BP05FourthRunningTypeEnvKeys:        []string{"TK_OPERATION_TYPE", "TK_TYPE_NUMBER_FILE", "TK_DATE_REQUEST", "TK_TIME_REQUEST", "TK_FILE_LIST"},
				BP06EnvKeyParams:                    []string{"id", "createdAt", "updatedAt", "version", "filesize", "name", "expiredAt", "categoryId", "userId", "path"},
				BP07FirstRunningTypeEnvKeys:         []string{"TK_BACKUP_DATE"},
				BP07SecondRunningTypeEnvKeys:        []string{"TK_BACKUP_SOURCE_CLASS"},
				BP07ThirdRunningTypeEnvKeys:         []string{"TK_BACKUP_TABLES"},
				MaxWaitTime:                         10000,
				RetryWaitTime:                       5000,
				MaxCountTime:                        3,
			},
			expect: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := tt.args.Validate()
			assert.Equal(t, tt.expect, result)
		})
	}
}
