#!/bin/bash
wget https://dl.google.com/go/go1.17.7.linux-amd64.tar.gz 
sudo tar -xvf go1.17.7.linux-amd64.tar.gz
sudo mv go /usr/local  
export GOROOT=/usr/local/go 
export GOPATH=$HOME/Projects/Proj1 
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH 


