name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up Go
        uses: ./.github/actions/setup-go-with-cache
      - name: Set up golangci-lint
        uses: ./.github/actions/setup-golangci-lint
      - name: Run golangci-lint
        run: |-
          golangci-lint run --out-format=github-actions -- \
            $(go work edit -json | jq -c -r '[.Use[].DiskPath] | map_values(. + "/...")[]')
